- src/common/schema.tsx
> chore: add explicit string return type for SchemaBuilder function

- src/components/common/Footer.tsx
- src/components/common/Header.tsx
- src/components/search/ResultSummary.tsx
- src/layouts/main.tsx
- src/templates/index.tsx
- vite.config.js
fix typo, fix import order, remove unused imports
> feat(): misc fixes

- package-lock.json
- package.json
- src/components/common/ErrorBoundaryWithAnalytics.tsx
- src/layouts/directory.tsx
- src/layouts/entity.tsx
- src/layouts/main.tsx
- yarn.lock
Prevents the entire react application from unmounting when an uncaught error occurs.
> feat: Add error boundary component.

- .github/workflows/updateVersion.yml
> feat: add GitHub action to update version.json with previous hash on merge to main.

- src/components/entity/Gallery.tsx
> feat(location): replace gallery dot with with flexbox properties

- package-lock.json
- package.json
- yarn.lock
> chore: update @yext/pages to beta.22

- localData/cog-internal-feature-static-file-generation-robots__en__cfcd208495d565ef66e7dff9f98764da.json
- localData/directory-city__en__82782b2605ed8fe8ba33d83a14680e56.json
- localData/directory-city__en__964b544d7823fc0633a060fd904176d0.json
- localData/directory-region__en__1210576f6b59e22e89e12a77f7a798a6.json
- localData/directory-region__en__a467079276adfd1e162839fb16569e38.json
- localData/directory-root__en__a9692a4fddb39679e182eede5b5da11b.json
- localData/locations__en__65706fda938b7baf4da9842dc9174581.json
- localData/locations__en__664e8e5fd84ed9aa7f23e3e0126e0e56.json
- localData/locations__en__bedacbff42a767c32534cfe5a2c697e2.json
- localData/locations__en__c4f729fae841e9c79ff7a1deb820586e.json
- localData/locations__en__e7879db810774abc8cd1000f29e868f7.json
- localData/mapping.json
- localData/search-page__en__d2148443c57696a3a7b3206170755172.json
allows use of starter without configuring account
resolves #168 
J=CR-3158
TEST=manual
> feat(): add localData directory

- src/common/head.tsx
updated dns-prefetch tags to be link els rather than meta ones
PC-214160
> feat(location): update dns-prefetch tags

- src/components/entity/FAQ.tsx
- changed faq toggles from divs to buttons
- prevent div from recieving focus when collapsed (https://bugzilla.mozilla.org/show_bug.cgi?id=1069739)
TEST=manual
> fix: resolve accessibility concerns with faq component

- localData/directory-city__en__82782b2605ed8fe8ba33d83a14680e56.json
- localData/directory-city__en__964b544d7823fc0633a060fd904176d0.json
- localData/directory-region__en__1210576f6b59e22e89e12a77f7a798a6.json
- localData/directory-region__en__a467079276adfd1e162839fb16569e38.json
- localData/directory-root__en__a9692a4fddb39679e182eede5b5da11b.json
- localData/locations__en__65706fda938b7baf4da9842dc9174581.json
- localData/locations__en__664e8e5fd84ed9aa7f23e3e0126e0e56.json
- localData/locations__en__bedacbff42a767c32534cfe5a2c697e2.json
- localData/locations__en__c4f729fae841e9c79ff7a1deb820586e.json
- localData/locations__en__e7879db810774abc8cd1000f29e868f7.json
- localData/locations__es__65706fda938b7baf4da9842dc9174581.json
- localData/mapping.json
- localData/search-page__en__d2148443c57696a3a7b3206170755172.json
- sites-config/features.json
- src/common/head.tsx
- src/templates/city.tsx
- src/templates/index.tsx
- src/templates/region.tsx
- src/templates/root.tsx
- src/templates/search.tsx
this config option is being deprecated because of
the amount of load it's placing on the system
J=CR-3185
TEST=manual
> feat: remove alternateLanguageFields config usage

- package-lock.json
- src/components/search/Facets/CheckboxOption.tsx
- src/components/search/Facets/ChevronIcon.tsx
- src/components/search/Facets/CollapsibleLabel.tsx
- src/components/search/Facets/CollapsibleSection.tsx
- src/components/search/Facets/FacetProps.tsx
- src/components/search/Facets/FacetTiltle.tsx
- src/components/search/Facets/Facets.tsx
- src/components/search/Facets/FacetsProvider.tsx
- src/components/search/Facets/FilterDivider.tsx
- src/components/search/Facets/FilterGroup.tsx
- src/components/search/Facets/FilterGroupContext.ts
- src/components/search/Facets/FilterGroupProvider.tsx
- src/components/search/Facets/FiltersContext.ts
- src/components/search/Facets/HierarchicalFacetContent.tsx
- src/components/search/Facets/HierarchicalFacetDisplay.tsx
- src/components/search/Facets/InvalidIcon.tsx
- src/components/search/Facets/NumberRangeFilter.ts
- src/components/search/Facets/NumericalFacetContent.tsx
- src/components/search/Facets/RangeInput.tsx
- src/components/search/Facets/SearchInput.tsx
- src/components/search/Facets/SelectableFieldValueFilter.ts
- src/components/search/Facets/StandardFacetContent.tsx
- src/components/search/Facets/filterutils.tsx
- src/components/search/Facets/search-operations.ts
- src/components/search/Facets/useComposedCssClasses.tsx
- src/components/search/Facets/useHierarchicalFacetTree.ts
- src/components/search/FacetsModal.tsx
this component frequently requires overrides and is quite difficult to customize, this should be an
easier starting point
J/T=none
TEST=manual
> feat: copy facet component from search ui library

- src/components/search/Facets/CollapsibleLabel.tsx
- src/components/search/Facets/HierarchicalFacetDisplay.tsx
- src/components/search/Facets/useComposedCssClasses.tsx
- src/i18n.ts
- src/layouts/main.tsx
- src/types/entities.d.ts
- tsconfig.json
> fix: fix type errors

- src/components/directory/DirectoryList.tsx
- src/layouts/directory.tsx
- src/templates/region.tsx
- src/templates/root.tsx
> feat(directory): remove skip level directory functionality

- src/components/entity/Core.tsx
- src/components/search/Locator.tsx
- src/config.ts
all implementations should be using their own key
J=CR-3187
TEST=manual
> feat: remove default google maps api key

- sites-config/features.json
- src/components/entity/Reviews.tsx
- src/layouts/entity.tsx
- src/templates/index.tsx
- src/types/entities.d.ts
> feat: fetch reviews client side

- sites-config/ci.json
> feat: allow nested static folders

- package.json
updated version fixes bug with holiday hours
J=none
TEST=none
> chore(): update schema-wrapper dependency

- src/components/directory/DirectorySearchBar.tsx
- src/config.ts
- src/layouts/search.tsx
this allows the test site to work without any changes
also adds logic for setting the experience version appropriately
TEST=manual
> feat: hardcode default experience ids

- package.json
- src/i18n.ts
> feat(location): removed language detector for i18n setup

- src/components/entity/Reviews.tsx
- src/components/entity/utils/fetchReviews.ts
- src/layouts/entity.tsx
> fix(location): only fetch reviews for current location

- .gitignore
> feat: add functionsMetadata.json to gitignore

- package-lock.json
- package.json
- src/templates/404.tsx
- src/types/components-404.d.ts
> feat: add 404 soft redirect logic

- package-lock.json
- package.json
- src/components/common/RTF.css
- src/components/common/RTF.tsx
- src/components/common/rtf-library/README.md
- src/components/common/rtf-library/handlers.ts
- src/components/common/rtf-library/index.ts
- src/components/common/rtf-library/mdast-util-yext/index.ts
- src/components/common/rtf-library/mdast-util-yext/mdast-node-types.ts
- src/components/common/rtf-library/mdast-util-yext/strikethrough.ts
- src/components/common/rtf-library/mdast-util-yext/subscript.ts
- src/components/common/rtf-library/mdast-util-yext/superscript.ts
- src/components/common/rtf-library/mdast-util-yext/underline.ts
- src/components/common/rtf-library/micromark-extension-yext/index.ts
- src/components/common/rtf-library/micromark-extension-yext/resolver-utils.ts
- src/components/common/rtf-library/micromark-extension-yext/strikethrough-subscript/index.ts
- src/components/common/rtf-library/micromark-extension-yext/strikethrough-subscript/resolver.ts
- src/components/common/rtf-library/micromark-extension-yext/strikethrough-subscript/tokenizer.ts
- src/components/common/rtf-library/micromark-extension-yext/superscript/index.ts
- src/components/common/rtf-library/micromark-extension-yext/superscript/resolver.ts
- src/components/common/rtf-library/micromark-extension-yext/superscript/tokenizer.ts
- src/components/common/rtf-library/micromark-extension-yext/underline/index.ts
- src/components/common/rtf-library/micromark-extension-yext/underline/resolver.ts
- src/components/common/rtf-library/micromark-extension-yext/underline/tokenizer.ts
> feat: implement RTF component for RTFv1 fields

- package-lock.json
- package.json
> feat: update @yext/schema-wrapper to 1.0.4

- package-lock.json
- package.json
- src/components/cards/DirectoryCard.tsx
- src/components/cards/LocatorCard.tsx
- src/components/entity/Hero.tsx
- src/layouts/city/configBuilder.tsx
- src/layouts/entity/configBuilder.tsx
- src/layouts/entity/template.tsx
- src/types/entities.d.ts
> feat: update hours component to handle timezones

- package-lock.json
- package.json
- src/components/cards/DirectoryCard.tsx
- src/components/cards/LocatorCard.tsx
- src/components/entity/Hero.tsx
- src/layouts/city/configBuilder.tsx
- src/layouts/entity/configBuilder.tsx
- src/layouts/entity/template.tsx
- src/types/entities.d.ts
Reverts yextconsulting/pages-starter-react-consulting#217
> Revert "feat: update hours component to handle timezones"

- src/common/head.tsx
> feat(head): add head script for passing entity ID to yextension

- package-lock.json
- package.json
J/T=none
TEST=manual
- npm run dev
- npm run dev -- --no-prod-url
- npm run prod
- platform deploy
> chore: update to yext/pages rc.9

- platform-config/config/pages/directory-manager/defaultDirectory.json
> chore: update dm resource with new required property

- src/common/getMapKey.ts
- src/common/head.tsx
- src/common/helpers.ts
- src/components/cards/TeamCard.tsx
- src/components/directory/DirectoryGrid.tsx
- src/components/directory/DirectoryList.tsx
- src/components/entity/Core.tsx
- src/layouts/entity/transformProps.tsx
- src/styles/theme.css
- src/types/entities.d.ts
Add formatted & href versions of mainPhone field by default
Remove default <abbr> element underline styling in address
Add Yext local dev key for mapbox maps
sort directory children by alphabetical by default
head.tsx updates
> feat(): misc updates:

- src/layouts/city/configBuilder.tsx
- src/layouts/entity/configBuilder.tsx
- src/layouts/region/configBuilder.tsx
- src/layouts/root/configBuilder.tsx
- src/layouts/search/configBuilder.tsx
From here: https://yext.slack.com/archives/C06GFG2PEPK/p1706539874262989
> feat: add slugField with default 'slug' value to config

- .github/workflows/buildTest.yml
- .github/workflows/checkTypesTest.yml
- .github/workflows/third_party_notices_check.yml
- package-lock.json
- package.json
- src/common/schema.tsx
- src/components/cards/EventCard.tsx
- src/components/cards/InsightCard.tsx
- src/components/cards/ProductCard.tsx
- src/components/common/Footer.tsx
- src/components/common/Header.tsx
- src/components/entity/About.tsx
- src/components/entity/Banner.tsx
- src/components/entity/FAQ.tsx
- src/components/entity/FAQs.tsx
- src/components/entity/FeaturedProduct.tsx
- src/components/entity/Gallery.tsx
- src/components/entity/Hero.tsx
- src/components/entity/Insights.tsx
- src/components/entity/Nearby.tsx
- src/components/entity/Promo.tsx
- src/components/search/CustomMarker.tsx
- src/layouts/entity/configBuilder.tsx
- src/types/entities.d.ts
- vite.config.js
> chore: upgrade @yext/pages and @yext/pages-components packages

- package-lock.json
- package.json
- src/components/common/ErrorBoundaryWithAnalytics.tsx
- Sentry alerting was never implemented in the pages starter causing errors to go unnoticed. This along with alerting infra updates will make these errors known on future pages imps.
J=none
TEST=manual
> feat(ErrorBoundaryWithAnalytics): add Sentry alerting
